### PR TITLE
Account for new PSR7 middleware of Cake 3.3.

### PR DESCRIPTION
**Pull request by ADmad**
Refs #441

### CODE REVIEW

**Comment by jippi** [comment]
tests look sad?

**Comment by ADmad** [comment]
Majority of the tests are broken on account of new phpunit release. Pinning a phpunit version in composer.json is also not easy since php 5.4 requires phpunit 4.x and php 5.5+ requires phpunit 5.x.

I have started fixing the test cases locally but it will take a while, lot of them need to be fixed.

**Comment by ADmad** [comment]
@jippi I have fixed all but one test. Hoping someone can help take care of the last one.

**Comment by jippi** [comment]
@ADmad good job! :)

**Comment by ADmad** [comment]
Merging this so that a new release which works with 3.3 can be done. The one failing test case can be taken care of later.

**Pull request merged**
