### PR TITLE
3.0 - replaced deprecated String class with CakeText

### PR DESCRIPTION
**Pull request by shahonseven**
replaced deprecated String class with CakeText

### CODE REVIEW

**Comment by jippi** [comment]
Please adjust the `App::uses` :)

**Comment by davidyell** [comment]
Yeah, this needs merging. I just hit this today as well.

**Comment by davidyell** [comment]
Rolled back my `cakephp/cakephp` to `2.7.11` to fix it in the meantime.

**Comment by jippi** [comment]
fixed it directly

**Comment by davidyell** [comment]
Thanks @jippi jippi

**Pull request closed without merging**
