### PR TITLE
Make JsonApiListener use schemas as described in the docs

### PR DESCRIPTION
**Pull request by bravo-kernel**
This PR adds the "custom dynamic schema" functionality as described in the docs.

### CODE REVIEW

**Comment by josegonzalez** [comment]
Can we specify a schema from a plugin?

**Comment by bravo-kernel** [comment]
Not yet even though I have thought about that. Should be relatively easy but for now making it feature perfect is just too much for me, I'm simply trying to get to the first release here. Ofcourse I am hoping this will get some traction so we can all benefit.

**Comment by josegonzalez** [comment]
No worries, just checking :)

**Comment by bravo-kernel** [comment]
No worries here, just acknowledging that there are other (much) more versed in the plugin area.

**Pull request merged**
