### PR TITLE
Fix docblock param types

### PR DESCRIPTION
**Pull request by dakota**
I think that this may correct #250. Will need to merge and see what happens.

### CODE REVIEW

**Comment by ADmad** [comment]
It doesn't :)  I really doubt scrutinizer depends on API docblocks tags.

**Comment by ADmad** [comment]
Oops I deleted the bugfix branch but here's the link to failed scrutinizer build https://scrutinizer-ci.com/g/FriendsOfCake/crud/inspections/0edf8859-87d9-493c-90d0-be7ece2b4fa0

**Comment by dakota** [comment]
I'm specifically refering to the failure with projects that use crud (As reported in #250) - https://scrutinizer-ci.com/g/alt3/cakephp-app-plusplus/inspections/c988a912-939b-4dd4-a0e3-6b4acf2ca2cc (Click on the `friendsofcake/crud` link)

The exact error reported there is:

```php
  [ErrorException]                                                                                                                                                   
  Notice: Undefined index: cake\event\event in vendor/scrutinizer/php-analyzer/src/Scrutinizer/PhpAnalyzer/Model/Repository/EntityTypeProvider.php line 131 
```

**Comment by dakota** [comment]
On second thought, the two errors are probably related and caused by the same thing.

**Pull request closed without merging**
