### PR TITLE
Adds config option for custom ExceptionRenderer class

### PR DESCRIPTION
**Pull request by bravo-kernel**
refs https://github.com/FriendsOfCake/crud/issues/407

### CODE REVIEW

**Comment by curtisgibby** [comment]
:+1: Any idea when this will make it into a release?

**Comment by bravo-kernel** [comment]
Thanks for the pointer @ADmad

**Comment by ADmad** [comment]
@curtisgibby New release tagged.

**Comment by curtisgibby** [comment]
Bump [.semver](https://github.com/FriendsOfCake/crud/blob/master/.semver)?

**Pull request merged**
