### PR TITLE
Support searching other datasource implementations

### PR DESCRIPTION
**Pull request by Marlinc**
Currently its not possible to use the search listener together
with either the Muffin Webservice plugin, the CakePHP ElasticSearch
plugin or any other datasource implementation.

This change removes the hard dependencies on the behaviours used
in with CakePHP's Table classes.

Signed-off-by: Marlin Cremers <m.cremers@cvo-technologies.com>

### CODE REVIEW

**Comment by ADmad** [comment]
To make phpstan happy please add the reported error to ignore list in `phpstan.neon`.

**Comment by ADmad** [comment]
@Marlinc ping

**Comment by Marlinc** [comment]
Lets see

**Comment by Marlinc** [comment]
Sorry for the long delay, any idea what's up with the failing tests @ADmad ?

**Pull request merged**
