### PR TITLE
Merge component's message config with action's message config.

### PR DESCRIPTION
**Pull request by ADmad**
This change for e.g. allows you to set "params" options just once instead of having to do it for every message type for every action.

One can do `$this->Crud->config('messages.params.class' => 'alert-message')` and have the class used for all messages.

### CODE REVIEW

**Comment by jadb** [comment]
I don't mind this but here's how I was doing it using events:

```php
    protected function _flashMessagesSetup()
    {
        $this->Crud->on('setFlash', function (Event $event) {
            $event->subject->params['class'] = 'alert-message';
        });
    }
```

**Comment by ADmad** [comment]
That's 3 lines too many for me to write in my app  :stuck_out_tongue:

**Comment by ADmad** [comment]
Seriously though I am reconsidering whether it's worth it to merge the options this way.

**Comment by lorenzo** [comment]
I prefer the even based approach. But having a test would be nice to speed the merge of this feature

**Comment by ADmad** [comment]
Using code below achieves what I want and let's BootstrapUI's FlashHelper handle the css class. So I am going to be lazy and close this for now rather than adding test cases for the change :stuck_out_tongue: 

```php
        $this->Crud->on('setFlash', function (Event $event) {
            unset($event->subject->params['class']);
            $event->subject->element = ltrim($event->subject->type);
        });
```

**Pull request closed without merging**
