### PR TITLE
Apitransformation number casting support inf

### PR DESCRIPTION
**Pull request by kimegede**
Fixing casting string to number - which can hit infinity, will not break `json_encode()` again.

In order to test Travis CI - I accidentl closed my previous PR... #245

### CODE REVIEW

**Comment by kimegede** [comment]
Booted up in a vm with PHP 5.3 but didn't get that error at all.
Now setup Travis CI to run for my fork of Crud too.

Giving me the errors on develop too. Looks like the same errors (still running)
Develop: https://travis-ci.org/kimegede/crud/builds/52391115
My code: https://travis-ci.org/kimegede/crud/builds/52390124

**Comment by kimegede** [comment]
Please point me in any direction :)

**Comment by kimegede** [comment]
...

**Comment by jippi** [comment]
The errors in 5.3 need to be fixed :)

**Comment by kimegede** [comment]
@jippi Did you see I got the same errors, with develop branch?

**Comment by jippi** [comment]
Can't merge it unless its fixed

Looks to be fairly trivial to fix though

**Comment by kimegede** [comment]
I'm still a big :question: about how my change made that failure?
When I can see the same in the develop [branch](https://travis-ci.org/kimegede/crud/builds/52391115) (See my previous comment: https://github.com/FriendsOfCake/crud/pull/246#issuecomment-76357884)

**Comment by jippi** [comment]
too old, not fixed

**Comment by kimegede** [comment]
@jippi still open questions.

**Comment by kimegede** [comment]
```php
MyController extends AppController {
....


	public function beforeFilter() {
		parent::beforeFilter();
	/**
	 * Cast number closure
	 * Verify integer it's below INF, before trying to JSON Encode
	 * As JSON Encode will fail.
	 *
	 * @see https://github.com/FriendsOfCake/crud/pull/245
	 * @see https://github.com/FriendsOfCake/crud/pull/246
	 * @param mixed $variable
	 * @param mixed $key
	 * @return mixed
	 */
		$castNumbersClosure = function($variable, $key) {
			if (!is_numeric($variable)) {
				return $variable;
			}
			$number = $variable + 0;
			// Check if number is below infinity
			return ($number < INF) ? $number : $variable;
		};
		$this->Crud->addListener('ApiTransformation', null, [
			'changeTime' => false,
			'castNumbers' => false,
			'valueMethods' => [$castNumbersClosure]
		]);
	}
}
```

**Pull request closed without merging**
