### PR TITLE
Properly call _trigger() with a Subject object

### PR DESCRIPTION
**Pull request by josegonzalez**
We previously were sending it an array.

### CODE REVIEW

**Comment by josegonzalez** [comment]
Fixes an issue produced by #263.

**Comment by ADmad** [comment]
Tests please.

**Comment by josegonzalez** [comment]
Sorry no, I'm not going to write tests for this. #263 was the thing that broke functionality - sans tests! - and was merged without complaints. I'll write a test for this when a test is written for the other stuff.

**Comment by ADmad** [comment]
Going by that logic we should stop bothering with tests henceforth. Everyone is going to make a mistake sometime, so we will just assign the blame and move on.

**Comment by josegonzalez** [comment]
What would the test be? That php throws an error if we pass in an array instead of a subject?

**Comment by jippi** [comment]
Yes

**Pull request merged**
