### PR TITLE
Replaced the deprecated EventManager methods

### PR DESCRIPTION
**Pull request by davidyell**
Updated event manager methods in the component.

### CODE REVIEW

**Comment by ADmad** [comment]
`BaseAction` and various test classes also use `attach()` instead of `on()` which should be updated.

**Comment by davidyell** [comment]
Haha, yeah, that's what got me embroiled in all that stuff with the tests to start with!

**Comment by ADmad** [comment]
Just concentrate on task at hand and don't muck around with other things :)

**Comment by ADmad** [comment]
Good job @davidyell :)

**Comment by davidyell** [comment]
:clap: 
Glad to help, got there in the end, thanks for the guidance.

**Pull request merged**
