### PR TITLE
update deprecated method

### PR DESCRIPTION
**Pull request by antograssiot**
``String`` Class has been replace by ``Text``
``validatePresence()`` has been renamed ``requirePresence()``

### CODE REVIEW

**Comment by jippi** [comment]
<3

**Comment by ADmad** [comment]
I am surprised there are no fails in spite of the core changes to validation. Not sure if that's good or bad :stuck_out_tongue:

**Comment by antograssiot** [comment]
also @Admad the tests where failing due to the String Clas call despite of the class_alias. Do you think it is a phpunit issue only ?

**Comment by ADmad** [comment]
That should work for tests too. It probably means the file which adds the class alias is not being loaded during tests.

**Pull request merged**
