### PR TITLE
ApiPaginationListener should use setConfig in beforeRender

### PR DESCRIPTION
**Pull request by frankvanhest**
After updating to crud tag 5.3.x the pagination failed due to a faulty replacement of the deprecated method InstanceConfigTrait::config(). 
At Crud\Listener\ApiPaginationListener line 71 the deprecated config method was used as a setter, but it was replaced as a getter.

### CODE REVIEW

**Comment by ADmad** [comment]
Looks good, can you add a test case to avoid regression?

**Comment by frankvanhest** [comment]
Sure, I'll write a test for it. It will be provided tomorrow evening (GMT)

**Comment by frankvanhest** [comment]
@ADmad A test has been added. Also the current tests for the ApiPaginationListener are updated so they work again after this change.

**Comment by ADmad** [comment]
@frankvanhest Thank you, merged and new release done.

**Pull request merged**
