### PR TITLE
Bump up to CakePHP 3.4

### PR DESCRIPTION
**Pull request by ADmad**
Refs #564 

@davidyell If you want to help out you can submit PR against the `cake-34` branch updating more usages of deprecated methods.
  
### Deprecated calls/methods to be update
* [x] `ServerRequest::method()`
* [x] `ServerRequest::param()`, `ServerRequest::$params`
* [x] `Response::statusCode()`
* [x] `EventDispatcherTrait::eventManager()`
* [x] `Event::$subject`

### CODE REVIEW

**Comment by davidyell** [comment]
I've had a quick look but I can't find any more deprecated methods, but I have submitted a PR with some documentation updates which hopefully is of some help.

**Comment by ADmad** [comment]
> I've had a quick look but I can't find any more deprecated methods, but I have submitted a PR with some documentation updates which hopefully is of some help.

I have added list of deprecated methods/properties which need to be updated in the PR description above. There are probably more.

> The only other thing I noticed was quite a lot of use of $event->subject instead of $event->subject(). 

Accessing the event subject as a public property has been [deprecated](https://github.com/cakephp/cakephp/blob/master/src/Event/Event.php#L95) too and updating it's usage is also within scope of this PR.

**Comment by davidyell** [comment]
Great work @admad I think I must have had something wrong with my local setup, as PHP Storm didn't see any of these as deprecated.

**Comment by ADmad** [comment]
Can't figure how these damn [exception renderer test failures](https://travis-ci.org/FriendsOfCake/crud/jobs/327835576#L575). They pass locally for me but on travis they fail with `$expected = ['success', 'data', 'queryLog'];` as well `$expected = ['success', 'data'];`

**Comment by josegonzalez** [comment]
That depends on the cakephp version, where i think we added `queryLog` at some point to the output of the exception renderer.

**Comment by ADmad** [comment]
@josegonzalez Since PR bumps up CakePHP to v3.4, travis builds are run on PHP 6.5+ and all use the same CakePHP version.

**Comment by ADmad** [comment]
I am giving up trying to please travis for now. The testsuite runs successfully for me locally, hence merging.

**Pull request merged**
