### PR TITLE
limit delete action methods

### PR DESCRIPTION
**Pull request by steefaan**
refs https://github.com/FriendsOfCake/crud/issues/338

### CODE REVIEW

**Comment by lorenzo** [comment]
Thanks!

**Comment by jippi** [comment]
I really dislike this - it prevents GET for /delete/ - its not even possible to opt-in to it - so its a huge breaking change - I'm going to revert it until we can come up with a way to introduce it that won't break existing apps and allow for people to opt in to GET, even though its not recommended

**Comment by josegonzalez** [comment]
:+1: what @jippi said. That's something I thought might be weird. Maybe just a configuration value and a check in `_handle` for it?

**Comment by lorenzo** [comment]
@jippi We can just release a new tag and let people convert their apps. It makes absolutely no sense to have a delete over GET, IMO

**Comment by josegonzalez** [comment]
@lorenzo I would do it for a fallback with a View to let people confirm the delete first.

**Comment by lorenzo** [comment]
@josegonzalez with the previous implementation it will delete before showing the view

**Pull request merged**
