### PR TITLE
Jsonapi split

### PR DESCRIPTION
**Pull request by bravo-kernel**
Prepares splitting JSON API to https://github.com/FriendsOfCake/crud-json-api

### CODE REVIEW

**Comment by bravo-kernel** [comment]
Just tested the split in my test-app and works as expected after changing the listeners to:

```php
            'listeners' => [
                'CrudJsonApi.JsonApi',
                'CrudJsonApi.Pagination',
                'Crud.ApiQueryLog'
            ]
```

Stripping out the docs next.

**Comment by jippi** [comment]
why? :)

**Comment by dakota** [comment]
There is still a fair amount of work that needs to happen with the json API stuff, this allows it to be developed without affecting the core CRUD release cycle

**Comment by ADmad** [comment]
@jippi The JsonApi related code gets regular updates while rest of the Crud is pretty stable. Having it separate makes maintenance easier and releases for both can be done independently as @dakota said.

**Comment by bravo-kernel** [comment]
@jippi it was requested exactly for the reasons above, I simply follow(ed)

**Comment by bravo-kernel** [comment]
Just to say.... I'm fine with not splitting and just deleting this PR too. Seems I've hitten the point were I feel I can have an opinion so no work lost either way ;)

**Comment by bravo-kernel** [comment]
- the [crud-json-api](https://github.com/FriendsOfCake/crud-json-api) repo is all set up
- docs are moved to https://crud-json-api.readthedocs.io/en/latest/

Everything is good to go as far as I can see, please let me know how to proceed.

**Comment by ADmad** [comment]
I would prefer having jsonapi separate.

**Comment by bravo-kernel** [comment]
If moved it would be nice if the four issues could be moved to the new repo as well. Has anybody ever pulled that off (successfully) before?

**Comment by ADmad** [comment]
I can take care of moving the issues.

**Comment by ADmad** [comment]
@jippi Any objections to merging this?

**Comment by ADmad** [comment]
Everything is setup on the new repo including docs for it on readthedocs.org.

**Comment by jippi** [comment]
no objections :) 

the only downside as i see the split will be that crud activity will look "stale" (since it's so stable and relatively bug free by now), and that can in some cases harm adoption rate.

not sure it would be a bad thing to tie crud and crud-json-api release cycle anyway, for pure-crud users it would just mean no problems :) 

but if you prefer the split, i have no objections at all :)

**Comment by ADmad** [comment]
We could come up with some new ideas to keep this repo look busy 😀

**Comment by ADmad** [comment]
@bravo-kernel  i'll take care of moving related issues to new repo later today.

**Comment by josegonzalez** [comment]
@bravo-kernel for reference, this is useful: https://github-issue-mover.appspot.com/

**Comment by davidyell** [comment]
Splitting seems like a good idea to me, I agree with the points raised here. It does make me wonder if the main Crud repo docs, needs a section explaining about the 'optional extras' which can be mixed in to Crud.

**Comment by ADmad** [comment]
A section in docs mentioning crud's ancillary plugins like jsonapi, crud-users, crud-view would be nice. We can also add them to composer's "suggests" section.

**Comment by bravo-kernel** [comment]
Totally agree with making crud plugins more visible by integrating them in the Crud docs, "suggests" are nice but end-users will probably read the docs mostly IMO. I feel #531 could be a good example.

**Comment by josegonzalez** [comment]
This should be updated in all FOC projects: https://github.com/FriendsOfCake/crud/blob/master/docs/conf.py#L25

**Comment by bravo-kernel** [comment]
Ideally with this list so JsonApi is included as well: https://github.com/FriendsOfCake/crud-json-api/blob/master/docs/conf.py#L25

**Comment by josegonzalez** [comment]
Might be worth just exposing a json endpoint on the foc site (github pages) that has a list of all FOC projects, and then curling it in that conf.py. That way we can expand the footer as necessary.

**Comment by bravo-kernel** [comment]
That would be more than awesome 💯

**Pull request merged**
