### PR TITLE
Hide exception details

### PR DESCRIPTION
**Pull request by jadb**
Exception info should only be shown in debug mode.

### CODE REVIEW

**Comment by ADmad** [comment]
Test failing

**Comment by jippi** [comment]
:-1: I prefer having some exception data leaked in non-debug mode, basically everything that does not reveal anything useful about the app, but allow the end-user to easier debug the issue - e.g. custom security exceptions, preconditions etc

**Comment by jadb** [comment]
@jippi what data exactly? 

https://gist.github.com/jadb/8aa5defd2081316e6f38

According to the gist above, when the trace is not included, the message and error code are already part of the data (outside of exception), so the only data leaked is the  exception renderer class. Have I missed something?

**Comment by jadb** [comment]
I'll correct myself, it shows the Validation exception class. But still, to an end-user, it doesn't give more information than the message/code it includes in the parent data already:

```
Crud\\Error\\Exception\\ValidationException
```
 and 

```
A validation error occurred
```

What do you think?

**Comment by jippi** [comment]
Seems legit :)

**Pull request merged**
