### PR TITLE
Text-Utility to String-Utility

### PR DESCRIPTION
**Pull request by bobmulder**
Found out you used the Text-Utility (`Cake\Utility\Text`) but it's used to be the String-Utility (`Cake\Utility\String`).

### CODE REVIEW

**Comment by lorenzo** [comment]
Text is the class that should be used

**Comment by bobmulder** [comment]
Well, I got an error, and it was fixed when using `String`

**Comment by jadb** [comment]
Probably need to update your cakephp core?

**Comment by bobmulder** [comment]
I did ;) I runned te most recent version...

2015-01-22 0:51 GMT+01:00 Jad Bitar <notifications@github.com>:

**Comment by ceeram** [comment]
Most recent release RC1 or most recent from dev-3.0? this change was made
after RC1

2015-01-22 2:41 GMT+01:00 bobmulder <notifications@github.com>:

**Pull request closed without merging**
