### PR TITLE
Switched validation error code, closes #337

### LINKED ISSUE #337: Validation Exception: HTTP Code 412 vs 422
Why is the HTTP code 412 (Precondition Failed) used for a validation exception and not 422 (Unprocessable Entity)?

It seems to me that 412 is for conditional headers.
>  The 412 (Precondition Failed) status code indicates that one or more
   conditions given in the request header fields evaluated to false when
   tested on the server.  This response code allows the client to place
   preconditions on the current resource state (its current
   representations and metadata) and, thus, prevent the request method
   from being applied if the target resource is in an unexpected state.
(http://tools.ietf.org/html/rfc7232#section-4.2)

And 422 for validation errors 
> The 422 (Unprocessable Entity) status code means the server
   understands the content type of the request entity (hence a
   415(Unsupported Media Type) status code is inappropriate), and the
   syntax of the request entity is correct (thus a 400 (Bad Request)
   status code is inappropriate) but was unable to process the contained
   instructions.  For example, this error condition may occur if an XML
   request body contains well-formed (i.e., syntactically correct), but
   semantically erroneous, XML instructions.
(http://tools.ietf.org/html/rfc4918#section-11.2)

### PR DESCRIPTION
**Pull request by jadb**
This will need to wait for cakephp/cakephp#8237 before being merged.

Note: there will be unrelated errors that are happening on other PRs too. Tried quickly resolving, no luck. Any pointers welcomed.

### CODE REVIEW

**Comment by jadb** [comment]
The related PR was merged on CakePHP.

**Comment by lorenzo** [comment]
Let's wait for a release containing that commit

**Comment by jippi** [comment]
should also bump composer.json to require that cakephp release version

**Comment by ADmad** [comment]
@jippi Done
@jadb You are welcome :stuck_out_tongue:

**Comment by jadb** [comment]
@ADmad thanks! they weren't related, were they?

**Comment by ADmad** [comment]
The fails were unrelated.

**Pull request merged**
