### PR TITLE
uuid for bulk actions

### PR DESCRIPTION
**Pull request by steefaan**
It's not possible to have a bulk delete for UUID based databases. This PR will fix it.

### CODE REVIEW

**Comment by steefaan** [comment]
I tried it with the following request data:

Not working:
```php
0 => '0acad6f2-b47e-4fc1-9086-cbc906dc45fd'
```

Working:
```php
'0acad6f2-b47e-4fc1-9086-cbc906dc45fd' => '0acad6f2-b47e-4fc1-9086-cbc906dc45fd'
```

**Comment by josegonzalez** [comment]
Can you add tests for this?

**Comment by steefaan** [comment]
Yes I will do it as soon as possible but not today, I need to leave now :)

**Comment by steefaan** [comment]
@josegonzalez Maybe it's a way to much but I need UUID's as base and BlogsFixture is integer based. What do you think? If you like it I will also add test cases for `toogleAction` and `setValueAction`.

**Comment by josegonzalez** [comment]
Yeah, more tests is good. Feel free to update your PR as desired :)

**Comment by steefaan** [comment]
@josegonzalez Done :)

**Comment by josegonzalez** [comment]
@ADmad thoughts on the pr?

**Pull request merged**
