### PR TITLE
Remove .semver file.

### PR DESCRIPTION
**Pull request by ADmad**
It's an unwanted chore updating it on each release which
is almost always forgotten.

### CODE REVIEW

**Comment by bravo-kernel** [comment]
:+1:

**Comment by jippi** [comment]
@ADmad my release tool uses the file :P i should just share the file :)

**Comment by josegonzalez** [comment]
Drop it from your release tool and use tags instead.

**Comment by ADmad** [comment]
@jippi My release tool is github's UI :stuck_out_tongue:

**Pull request merged**
