### PR TITLE
Add json api query support and include support

### PR DESCRIPTION
**Pull request by dakota**
This adds support to the json api for parsing query parameters. Included as part of this is ability to pass the `include` query parameter to conditionally load relationships.

### CODE REVIEW

**Comment by bravo-kernel** [comment]
Epic PR 💯 

FWIW I am getting the exact same Travis fails here #506 and haven't been able to figure out what causes it yet. So far I see no differences between the previously successful builds and these all-of-a-sudden-fails (I am using the 5.6 to troubleshoot)

**Comment by jippi** [comment]
I think it should be possible / required to whitelist the associations that you can pass into `include` - and not blow it wide open by default :)

**Comment by dakota** [comment]
> I think it should be possible / required to whitelist the associations that you can pass into include - and not blow it wide open by default :)

I definately agree, and will be adding that. Wanted to get the PR open in the meantime

**Comment by bravo-kernel** [comment]
@dakota since this got discussed on Slack... will this include full [sparse fieldsets](http://jsonapi.org/format/#fetching-sparse-fieldsets) functionality?

    GET /articles?include=author&fields[articles]=title,body&fields[people]=name

**Comment by dakota** [comment]
@bravo-kernel It does not, and will not, **BUT** it lays the foundation to add that functionality, as well as [filtering](http://jsonapi.org/format/#fetching-filtering). I will be working on that next, as a separate PR. Don't want to introduce too much in a single PR

**Comment by bravo-kernel** [comment]
I thought so by looking at the code but just wanted to make sure, thanks

**Comment by bravo-kernel** [comment]
I ❤️ it. 

I don't have time to complete a full integration test but here's some initial feedback to start with.

All tested against my `CountriesController` `index` action, all my custom behaviors etc. disabled.

- [X] single-include-hasMany
- [ ] single-include-belongsTo
- [ ] multi-include-hasMany-and-belongsTo
- [ ] usability

### single-include-hasMany (OK)
 
Tested against `/countries?include=cultures`.

- OK: the `relationships` node contains related data as expected (per resource)
- OK: the `included` node gets rendered as expected

```json
{
  "data": [
    {
      "type": "countries",
      "id": "1",
      "attributes": {
        "code": "NL",
        "name": "The Netherlands",
        "native": "Nederland",
        "slug": "nl",
        "approved": true,
        "created": "2017-02-25T20:40:40+00:00",
        "modified": "2017-02-25T20:40:40+00:00"
      },
      "relationships": {
        "cultures": {
          "data": [
            {
              "type": "cultures",
              "id": "1"
            }
          ],
          "links": {
            "self": "/cultures?country_id=1"
          }
        }
      },
      "links": {
        "self": "/countries/1"
      }
    }
  ],
  "included": [
    {
      "type": "cultures",
      "id": "1",
      "attributes": {
        "code": "nl-NL",
        "name": "Dutch",
        "native": "Nederlands",
        "slug": "nl-nl",
        "country_id": 1,
        "approved": true,
        "created": "2017-02-25T20:40:40+00:00",
        "modified": "2017-02-25T20:40:40+00:00"
      }
    }
  ]
}
```

### single-include-belongsTo (Not OK)

Tested with `/countries?include=currencies

- OK: the `relationships` node contains related data as expected (per resource)
- NOK: the `included` node does not get rendered

```json
{
  "data": [
    {
      "type": "countries",
      "id": "1",
      "attributes": {
        "code": "NL",
        "name": "The Netherlands",
        "native": "Nederland",
        "slug": "nl",
        "approved": true,
        "created": "2017-02-25T20:40:40+00:00",
        "modified": "2017-02-25T20:40:40+00:00"
      },
      "relationships": {
        "currency": {
          "data": {
            "type": "currencies",
            "id": "1"
          },
          "links": {
            "self": "/currencies/1"
          }
        }
      },
      "links": {
        "self": "/countries/1"
      }
    }
  ]
}
```

###  multi-include-hasMany-and-belongsTo (Not OK)

Tested with `/countries?include=cultures,currencies`:

- OK: the `relationships` node contains related data as expected (per resource)
- OK: the `included` node gets rendered with hasMany data
- NOK: the belongsTo data is missing from the `included` node

```json
{
  "data": [
    {
      "type": "countries",
      "id": "1",
      "attributes": {
        "code": "NL",
        "name": "The Netherlands",
        "native": "Nederland",
        "slug": "nl",
        "approved": true,
        "created": "2017-02-25T20:40:40+00:00",
        "modified": "2017-02-25T20:40:40+00:00"
      },
      "relationships": {
        "currency": {
          "data": {
            "type": "currencies",
            "id": "1"
          },
          "links": {
            "self": "/currencies/1"
          }
        },
        "cultures": {
          "data": [
            {
              "type": "cultures",
              "id": "1"
            }
          ],
          "links": {
            "self": "/cultures?country_id=1"
          }
        }
      },
      "links": {
        "self": "/countries/1"
      }
    }
  ],
  "included": [
    {
      "type": "cultures",
      "id": "1",
      "attributes": {
        "code": "nl-NL",
        "name": "Dutch",
        "native": "Nederlands",
        "slug": "nl-nl",
        "country_id": 1,
        "approved": true,
        "created": "2017-02-25T20:40:40+00:00",
        "modified": "2017-02-25T20:40:40+00:00"
      }
    }
  ]
}
```

### Usability

I'm ashamed to admit but I was unable to figure out (from the stack trace) which one of the three resources in `?include=cultures,donkey,currencies` was causing the following error. I think it would be very useful if the detail message would mention which resource(s) are failing (if even possible ofcourse).

```json
  "errors": [
    {
      "code": "400",
      "title": "Bad Request",
      "detail": "Invalid relationship path supplied in include parameter"
```

**Comment by bravo-kernel** [comment]
I've added a few more tests. 

I hope this also makes clear how badly I need to get the integration tests working for JsonApiListener (#513).

**Comment by dakota** [comment]
@bravo-kernel Made quite a few changes now.

Firstly, all your supplied test cases are working (With integration tests 🎉 )

I have also started work on supporting arbitrarily deeply nested includes/contains. Will get that finished soon.

**Comment by bravo-kernel** [comment]
### Listener config

I copy-pasted the following from your docs example and it giving me this error (cake 3.3.9);

> "code": "500",
> "title": "Internal Server Error",
> "detail": "Call to undefined method Crud\\Listener\\JsonApiListener::setConfig()"

```php
    public function index()
    {
        $this->Crud
          ->listener('jsonApi')
          ->setConfig('queryParameters.include.blacklist', ['countries']);

        $this->Crud->on('beforePaginate', function (Event $event) {
        });

        return $this->Crud->execute();
    }
```

### Stack trace

<details>

```json
{
  "errors": [
    {
      "code": "500",
      "title": "Internal Server Error",
      "detail": "Call to undefined method Crud\\Listener\\JsonApiListener::setConfig()"
    }
  ],
  "debug": {
    "class": "Error",
    "trace": [
      {
        "file": "/home/vagrant/projects/alt3-api/vendor/friendsofcake/crud/src/Controller/ControllerTrait.php",
        "line": 51,
        "function": "call_user_func_array",
        "args": [
          [
            {
              "paginate": {
                "sortWhitelist": [
                  "code",
                  "name"
                ]
              },
              "name": "Currencies",
              "helpers": [],
              "request": {
                "params": {
                  "plugin": null,
                  "controller": "Currencies",
                  "action": "index",
                  "_ext": null,
                  "pass": [],
                  "_method": "GET",
                  "_matchedRoute": "/currencies",
                  "isAjax": false
                },
                "data": [],
                "query": [],
                "cookies": {
                  "CAKEPHP": "a93dsl3393955f5lphabses856",
                  "csrfToken": "0d2c72f16a2aaabf9a38f18fa8974f66a2d87967"
                },
                "url": "currencies",
                "base": "",
                "webroot": "/",
                "here": "/currencies",
                "trustProxy": false
              },
              "response": {},
              "autoRender": true,
              "components": [],
              "View": null,
              "plugin": null,
              "passedArgs": [],
              "modelClass": "Currencies",
              "viewClass": null,
              "viewVars": [],
              "dispatchComponents": {
                "Crud": true
              },
              "RequestHandler": {
                "enabled": true,
                "response": {},
                "ext": null,
                "request": {
                  "params": {
                    "plugin": null,
                    "controller": "Currencies",
                    "action": "index",
                    "_ext": null,
                    "pass": [],
                    "_method": "GET",
                    "_matchedRoute": "/currencies",
                    "isAjax": false
                  },
                  "data": [],
                  "query": [],
                  "cookies": {
                    "CAKEPHP": "a93dsl3393955f5lphabses856",
                    "csrfToken": "0d2c72f16a2aaabf9a38f18fa8974f66a2d87967"
                  },
                  "url": "currencies",
                  "base": "",
                  "webroot": "/",
                  "here": "/currencies",
                  "trustProxy": false
                },
                "components": []
              },
              "Crud": {
                "request": {
                  "params": {
                    "plugin": null,
                    "controller": "Currencies",
                    "action": "index",
                    "_ext": null,
                    "pass": [],
                    "_method": "GET",
                    "_matchedRoute": "/currencies",
                    "isAjax": false
                  },
                  "data": [],
                  "query": [],
                  "cookies": {
                    "CAKEPHP": "a93dsl3393955f5lphabses856",
                    "csrfToken": "0d2c72f16a2aaabf9a38f18fa8974f66a2d87967"
                  },
                  "url": "currencies",
                  "base": "",
                  "webroot": "/",
                  "here": "/currencies",
                  "trustProxy": false
                },
                "response": {},
                "components": []
              },
              "Auth": {
                "components": [
                  "RequestHandler",
                  "Flash"
                ],
                "allowedActions": [
                  "home",
                  "index",
                  "view",
                  "index",
                  "view"
                ],
                "request": {
                  "params": {
                    "plugin": null,
                    "controller": "Currencies",
                    "action": "index",
                    "_ext": null,
                    "pass": [],
                    "_method": "GET",
                    "_matchedRoute": "/currencies",
                    "isAjax": false
                  },
                  "data": [],
                  "query": [],
                  "cookies": {
                    "CAKEPHP": "a93dsl3393955f5lphabses856",
                    "csrfToken": "0d2c72f16a2aaabf9a38f18fa8974f66a2d87967"
                  },
                  "url": "currencies",
                  "base": "",
                  "webroot": "/",
                  "here": "/currencies",
                  "trustProxy": false
                },
                "response": {},
                "session": {}
              },
              "Alt3Api": {
                "request": {
                  "params": {
                    "plugin": null,
                    "controller": "Currencies",
                    "action": "index",
                    "_ext": null,
                    "pass": [],
                    "_method": "GET",
                    "_matchedRoute": "/currencies",
                    "isAjax": false
                  },
                  "data": [],
                  "query": [],
                  "cookies": {
                    "CAKEPHP": "a93dsl3393955f5lphabses856",
                    "csrfToken": "0d2c72f16a2aaabf9a38f18fa8974f66a2d87967"
                  },
                  "url": "currencies",
                  "base": "",
                  "webroot": "/",
                  "here": "/currencies",
                  "trustProxy": false
                },
                "response": {},
                "components": []
              },
              "Prg": {
                "request": {
                  "params": {
                    "plugin": null,
                    "controller": "Currencies",
                    "action": "index",
                    "_ext": null,
                    "pass": [],
                    "_method": "GET",
                    "_matchedRoute": "/currencies",
                    "isAjax": false
                  },
                  "data": [],
                  "query": [],
                  "cookies": {
                    "CAKEPHP": "a93dsl3393955f5lphabses856",
                    "csrfToken": "0d2c72f16a2aaabf9a38f18fa8974f66a2d87967"
                  },
                  "url": "currencies",
                  "base": "",
                  "webroot": "/",
                  "here": "/currencies",
                  "trustProxy": false
                },
                "response": {},
                "components": []
              }
            },
            "index"
          ],
          []
        ]
      },
      {
        "file": "/home/vagrant/projects/alt3-api/vendor/cakephp/cakephp/src/Http/ActionDispatcher.php",
        "line": 122,
        "function": "invokeAction",
        "class": "App\\Controller\\AppController",
        "type": "->",
        "args": []
      },
      {
        "file": "/home/vagrant/projects/alt3-api/vendor/cakephp/cakephp/src/Http/ActionDispatcher.php",
        "line": 96,
        "function": "_invoke",
        "class": "Cake\\Http\\ActionDispatcher",
        "type": "->",
        "args": [
          {
            "paginate": {
              "sortWhitelist": [
                "code",
                "name"
              ]
            },
            "name": "Currencies",
            "helpers": [],
            "request": {
              "params": {
                "plugin": null,
                "controller": "Currencies",
                "action": "index",
                "_ext": null,
                "pass": [],
                "_method": "GET",
                "_matchedRoute": "/currencies",
                "isAjax": false
              },
              "data": [],
              "query": [],
              "cookies": {
                "CAKEPHP": "a93dsl3393955f5lphabses856",
                "csrfToken": "0d2c72f16a2aaabf9a38f18fa8974f66a2d87967"
              },
              "url": "currencies",
              "base": "",
              "webroot": "/",
              "here": "/currencies",
              "trustProxy": false
            },
            "response": {},
            "autoRender": true,
            "components": [],
            "View": null,
            "plugin": null,
            "passedArgs": [],
            "modelClass": "Currencies",
            "viewClass": null,
            "viewVars": [],
            "dispatchComponents": {
              "Crud": true
            },
            "RequestHandler": {
              "enabled": true,
              "response": {},
              "ext": null,
              "request": {
                "params": {
                  "plugin": null,
                  "controller": "Currencies",
                  "action": "index",
                  "_ext": null,
                  "pass": [],
                  "_method": "GET",
                  "_matchedRoute": "/currencies",
                  "isAjax": false
                },
                "data": [],
                "query": [],
                "cookies": {
                  "CAKEPHP": "a93dsl3393955f5lphabses856",
                  "csrfToken": "0d2c72f16a2aaabf9a38f18fa8974f66a2d87967"
                },
                "url": "currencies",
                "base": "",
                "webroot": "/",
                "here": "/currencies",
                "trustProxy": false
              },
              "components": []
            },
            "Crud": {
              "request": {
                "params": {
                  "plugin": null,
                  "controller": "Currencies",
                  "action": "index",
                  "_ext": null,
                  "pass": [],
                  "_method": "GET",
                  "_matchedRoute": "/currencies",
                  "isAjax": false
                },
                "data": [],
                "query": [],
                "cookies": {
                  "CAKEPHP": "a93dsl3393955f5lphabses856",
                  "csrfToken": "0d2c72f16a2aaabf9a38f18fa8974f66a2d87967"
                },
                "url": "currencies",
                "base": "",
                "webroot": "/",
                "here": "/currencies",
                "trustProxy": false
              },
              "response": {},
              "components": []
            },
            "Auth": {
              "components": [
                "RequestHandler",
                "Flash"
              ],
              "allowedActions": [
                "home",
                "index",
                "view",
                "index",
                "view"
              ],
              "request": {
                "params": {
                  "plugin": null,
                  "controller": "Currencies",
                  "action": "index",
                  "_ext": null,
                  "pass": [],
                  "_method": "GET",
                  "_matchedRoute": "/currencies",
                  "isAjax": false
                },
                "data": [],
                "query": [],
                "cookies": {
                  "CAKEPHP": "a93dsl3393955f5lphabses856",
                  "csrfToken": "0d2c72f16a2aaabf9a38f18fa8974f66a2d87967"
                },
                "url": "currencies",
                "base": "",
                "webroot": "/",
                "here": "/currencies",
                "trustProxy": false
              },
              "response": {},
              "session": {}
            },
            "Alt3Api": {
              "request": {
                "params": {
                  "plugin": null,
                  "controller": "Currencies",
                  "action": "index",
                  "_ext": null,
                  "pass": [],
                  "_method": "GET",
                  "_matchedRoute": "/currencies",
                  "isAjax": false
                },
                "data": [],
                "query": [],
                "cookies": {
                  "CAKEPHP": "a93dsl3393955f5lphabses856",
                  "csrfToken": "0d2c72f16a2aaabf9a38f18fa8974f66a2d87967"
                },
                "url": "currencies",
                "base": "",
                "webroot": "/",
                "here": "/currencies",
                "trustProxy": false
              },
              "response": {},
              "components": []
            },
            "Prg": {
              "request": {
                "params": {
                  "plugin": null,
                  "controller": "Currencies",
                  "action": "index",
                  "_ext": null,
                  "pass": [],
                  "_method": "GET",
                  "_matchedRoute": "/currencies",
                  "isAjax": false
                },
                "data": [],
                "query": [],
                "cookies": {
                  "CAKEPHP": "a93dsl3393955f5lphabses856",
                  "csrfToken": "0d2c72f16a2aaabf9a38f18fa8974f66a2d87967"
                },
                "url": "currencies",
                "base": "",
                "webroot": "/",
                "here": "/currencies",
                "trustProxy": false
              },
              "response": {},
              "components": []
            }
          }
        ]
      },
      {
        "file": "/home/vagrant/projects/alt3-api/vendor/cakephp/cakephp/src/Routing/Dispatcher.php",
        "line": 60,
        "function": "dispatch",
        "class": "Cake\\Http\\ActionDispatcher",
        "type": "->",
        "args": [
          {
            "params": {
              "plugin": null,
              "controller": "Currencies",
              "action": "index",
              "_ext": null,
              "pass": [],
              "_method": "GET",
              "_matchedRoute": "/currencies",
              "isAjax": false
            },
            "data": [],
            "query": [],
            "cookies": {
              "CAKEPHP": "a93dsl3393955f5lphabses856",
              "csrfToken": "0d2c72f16a2aaabf9a38f18fa8974f66a2d87967"
            },
            "url": "currencies",
            "base": "",
            "webroot": "/",
            "here": "/currencies",
            "trustProxy": false
          },
          {}
        ]
      },
      {
        "file": "/home/vagrant/projects/alt3-api/webroot/index.php",
        "line": 36,
        "function": "dispatch",
        "class": "Cake\\Routing\\Dispatcher",
        "type": "->",
        "args": [
          {
            "params": {
              "plugin": null,
              "controller": "Currencies",
              "action": "index",
              "_ext": null,
              "pass": [],
              "_method": "GET",
              "_matchedRoute": "/currencies",
              "isAjax": false
            },
            "data": [],
            "query": [],
            "cookies": {
              "CAKEPHP": "a93dsl3393955f5lphabses856",
              "csrfToken": "0d2c72f16a2aaabf9a38f18fa8974f66a2d87967"
            },
            "url": "currencies",
            "base": "",
            "webroot": "/",
            "here": "/currencies",
            "trustProxy": false
          },
          {}
        ]
      }
    ]
  }
}
```

</details>

**Comment by dakota** [comment]
@bravo-kernel Probably because you are using CakePHP 3.3 still :) Will get that updated

**Comment by bravo-kernel** [comment]
The blacklist works as expected **except**... when there already is a `contain` in the action itself, like shown below. I expected `included` to be empty due to the blacklist-config  winning. If I'm missing the point here please elaborate.

```php
    public function index()
    {
        $this->Crud
          ->listener('jsonApi')
          ->config('queryParameters.include.blacklist', ['currencies', 'cultures']);

         $this->Crud->on('beforePaginate', function (Event $event) {
            $event->subject()->query->contain([
                'Currencies',
                'Cultures'
            ]);
         });

        return $this->Crud->execute();
    }
```

**Comment by bravo-kernel** [comment]
Just tested the `view` action with your include and it works like a charm 👍 

However, I did notice that the include does not accept/respect my dasherized models and throws the following error when using the expected `/users/1?include=user-profiles`

> "code": "400",
> "title": "Bad Request",
> "detail": "Invalid relationship path 'user-profiles' supplied in include parameter"

Changing the include to underscored `/users/1?include=user_profiles` makes it work but produces incorrect underscored json as can be seen below (where only the self-link is using correct dash):

<details> 

```json
{
  "data": {
    "type": "users",
    "id": "1",
    "attributes": {
      "email": "bravo@kernel.com",
      "username": null,
      "slug": null,
      "confirmed": false,
      "created": "2017-03-08T14:32:31+00:00",
      "modified": "2017-03-08T14:32:31+00:00"
    },
    "relationships": {
      "user_profile": {
        "data": {
          "type": "user_profiles",
          "id": "333"
        },
        "links": {
          "self": "/user-profiles/view/333"
        }
      }
    },
    "links": {
      "self": "/users/1"
    }
  },
  "included": [
    {
      "type": "user_profiles",
      "id": "333",
      "attributes": {
        "newsletter": false,
        "notifications": false,
        "created": "2017-03-08T14:32:31+00:00",
        "modified": "2017-03-08T14:32:31+00:00"
      }
    }
  ]
}
```
<details>

**Comment by dakota** [comment]
> The blacklist works as expected except... when there already is a contain in the action itself

This is the expected behaviour. The blacklist/whitelist ONLY affects the `include` query parameter. If no query parameter is supplied then the `include` config option, or auto-determination is used as previously.

**Comment by bravo-kernel** [comment]
Thanks for explaining mr. @dakota. Since there are no more things on my list I would say this is functionally good to go. Awesome job 💯

**Comment by dakota** [comment]
If everybody is happy, I'll go ahead and merge?

**Comment by jippi** [comment]
Thanks @dakota !

**Comment by bravo-kernel** [comment]
👏

**Comment by ADmad** [comment]
Does this warrant a new minor release or a bugfix release should suffice?

**Comment by dakota** [comment]
Depends on how strict we are about feature additions? It doesn't really change how the default behaviour worked

**Pull request merged**
