### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by davidyell**
Updated version notice

### CODE REVIEW

**Comment by jadb** [comment]
Shouldn't this target the https://github.com/FriendsOfCake/crud/tree/cake2 branch?

**Comment by bcrowe** [comment]
@jadb Nope.  Crud 3 is Cake 2. :smile:

**Comment by jadb** [comment]
Ah right! Merging then.

**Comment by davidyell** [comment]
Yeah 2 is 3 and 3 is 4. :stuck_out_tongue:

**Comment by ADmad** [comment]
@jadb `cake2` branch was same as `3.0`. I had forgotten that I had already created `3.0`. Deleted `cake2` now.

**Pull request merged**
