### PR TITLE
Catch exception and ignore it in ApiQueryLogListener

### PR DESCRIPTION
**Pull request by Spriz**
Refs #341

### CODE REVIEW

**Comment by lorenzo** [comment]
Thanks

**Comment by ADmad** [comment]
I am curious how do we end up with non-existent datasources when `_getSources()` uses `ConnectionManager::configured()` to get the list.

**Comment by lorenzo** [comment]
The aliasing done by the fixture manager when running tests

**Comment by ADmad** [comment]
@lorenzo Aren't the params to `ConnectionManager::alias()` swapped [here](https://github.com/cakephp/cakephp/blob/master/src/TestSuite/Fixture/FixtureManager.php#L141)?  As per API the first param is supposed to be actual name and second param the alias.

**Comment by lorenzo** [comment]
@ADmad No... they order is misleading to me too. But the order is correct.

**Pull request merged**
