### PR TITLE
delete second find()

### PR DESCRIPTION
**Pull request by steefaan**
refs https://github.com/FriendsOfCake/crud/pull/324

### CODE REVIEW

**Comment by lorenzo** [comment]
A bug in cake needs to be fixed before this PR is merged

**Comment by steefaan** [comment]
@lorenzo Already works for me with a single `find()` in Cake 3.1

**Comment by jadb** [comment]
I agree with @steefaan  - been working for me for a while (since `3.1.x-dev`).

**Comment by lorenzo** [comment]
There is still a bug, I will try to fix it tomorrow in cakephp

**Comment by ADmad** [comment]
This is no longer an issue on current master.

**Pull request closed without merging**
