### PR TITLE
Add SerializeTrait to View and Edit Actions

### PR DESCRIPTION
**Pull request by raul338**
The code in the docs throw exceptions
```php
$this->Crud->action()->serialize();
// Call to undefined method Crud\Action\ViewAction::serialize()
```
This PR fix that

### CODE REVIEW

**Comment by ADmad** [comment]
Tests needed.

**Comment by raul338** [comment]
Tests added. I add a simple test for all actions

**Comment by raul338** [comment]
Should I do anything else?

**Comment by ADmad** [comment]
Sorry but your tests are pointless. You should be asserting that view var `_serialize` contains the key you set when calling `serialize()` method. And since the action's serialize config is used only by `ApliListener` your tests should be in `ApiListenerTest`.

**Comment by raul338** [comment]
Ok, I'll try on the weekend

**Comment by raul338** [comment]
Should I do something else?

**Comment by raul338** [comment]
Could you release a bugfix release please?

**Comment by ADmad** [comment]
Done

**Pull request merged**
