### PR TITLE
Lower CakePHP version requiment to 3.5.

### PR DESCRIPTION
**Pull request by ADmad**

### CODE REVIEW

**Comment by ADmad** [comment]
Update to .travis.yml coming up for testing against lowest version.

**Comment by ADmad** [comment]
Done

**Comment by josegonzalez** [comment]
Why this change @ADmad ?

**Comment by ADmad** [comment]
So that current minor can work with Cake 3.5 as well as 3.6 without issues/warnings and bumping min. Cake version dependency to 3.6 can be avoided.

**Pull request merged**
