### PR TITLE
Add saveMethod and saveOptions keys on $subject.

### LINKED ISSUE #503: Missing subject keys saveMethod and saveOptions from EditAction.
The [docs](http://crud.readthedocs.io/en/latest/actions/edit.html#crud-beforesave) says that getSubject() returns entity, saveMethod and saveOptions, but they aren't set on EditAction file.

I think adding these 2 lines into the [`_put()` method](https://github.com/FriendsOfCake/crud/blob/master/src/Action/EditAction.php#L110) fix the problem.
```php
$subject->set(['saveMethod' => $this->saveMethod()]);
$subject->set(['saveOptions' => $this->saveOptions()]);
```

### PR DESCRIPTION
**Pull request by alysson-azevedo**
This issue should fix #503.

### CODE REVIEW

**Comment by ADmad** [comment]
Tests needed for the change.

**Comment by alysson-azevedo** [comment]
Then nevermind.

**Comment by jippi** [comment]
lol

**Comment by davidyell** [comment]
If tests are a requirement then that should probably be added to currently non-existant 'Contribution notes' section of the readme I'd think.

**Comment by alysson-azevedo** [comment]
In the [docs](http://crud.readthedocs.io/en/latest/#bugs) says that tests are optional, that's why when i found the error, i just edited the source file using the github's editor with the fix. It was the same on #514.

I don't even cloned this repo in my workspace.
So i'm sorry for being rude before.

**Pull request closed without merging**
